apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  {{- template "vault.labels" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: vault-port
    port: 80
    targetPort: 8200
    protocol: TCP