# Default values for vault.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: registry.hub.docker.com/library/vault
  tag: "1.1.1"
  pullPolicy: IfNotPresent

gcs:
  bucket:

kms:
  project:
  region:
  keyRing:
  cryptoKey:

ingress:
  enabled: true
  class: internal
  # domainName: 
  annotations: {}